### PR TITLE
[CONFIG] - Issue #5 - removed debug dependency

### PR DESCRIPTION
**Pull request by michaelBenin**

### CODE REVIEW

**Comment by michaelBenin** [comment]
Ok with you if we change the extension to js from es6? Will also update main in package.json. 

Can do this in another pr if it's ok with you.

**Comment by shuvalov-anton** [comment]
Thank you)

**Comment by shuvalov-anton** [comment]
I'm going to release it for few days

**Comment by shuvalov-anton** [comment]
@michaelBenin yay, I've landed it to npm just now :D

**Pull request merged**
